package driver

import (
	"encoding/base64"
	"fmt"
	"strings"
	"time"

	"github.com/docker/machine/libmachine/drivers"
	"github.com/docker/machine/libmachine/log"

	"github.com/lore09/pve-rancher-driver/pkg/proxmox"
)

// mountOptions are the fstab options used for every data disk. nofail plus a
// device timeout keeps a node bootable if a disk ever goes missing, instead of
// dropping it into emergency mode where Rancher cannot reach it.
const mountOptions = "defaults,nofail,x-systemd.device-timeout=30s"

// renderDiskSetupScript builds the bash script that formats, mounts and
// persists the data disks inside the guest.
//
// Disks are found by serial (set by the client from DiskSpec.Label), never by
// kernel name: sd* ordering is not stable once a VM has more than one data
// disk. Every value interpolated here has already passed the shell-safety
// whitelist in ParseDataDisks.
//
// Callers must filter to disks where Spec.NeedsGuestSetup() is true; a disk
// with fs=none has no block in the script.
func renderDiskSetupScript(disks []proxmox.AttachedDisk) string {
	var b strings.Builder
	b.WriteString("#!/bin/bash\n")
	b.WriteString("# Generated by the pve node driver. Safe to re-run: a device that already has a\n")
	b.WriteString("# filesystem is never reformatted and an fstab entry is never duplicated.\n")
	b.WriteString("set -euo pipefail\n")

	for _, disk := range disks {
		spec := disk.Spec
		if !spec.NeedsGuestSetup() {
			continue
		}
		b.WriteString(fmt.Sprintf("\n# %s -> %s (%s, serial %s)\n", disk.Device, spec.Mount, spec.FS, spec.Label))
		b.WriteString(fmt.Sprintf("dev=$(lsblk -ndo NAME,SERIAL | awk '$2==\"%s\"{print \"/dev/\"$1}')\n", spec.Label))
		b.WriteString("if [ -z \"$dev\" ]; then\n")
		b.WriteString(fmt.Sprintf("  echo \"pve: no block device with serial %s\" >&2\n", spec.Label))
		b.WriteString("  exit 1\n")
		b.WriteString("fi\n")
		b.WriteString("if ! blkid \"$dev\" >/dev/null 2>&1; then\n")
		b.WriteString(fmt.Sprintf("  mkfs.%s -q -L %s \"$dev\"\n", spec.FS, spec.Label))
		b.WriteString("fi\n")
		b.WriteString(fmt.Sprintf("mkdir -p %s\n", spec.Mount))
		b.WriteString(fmt.Sprintf("if ! grep -qF ' %s ' /etc/fstab; then\n", spec.Mount))
		b.WriteString(fmt.Sprintf("  echo 'LABEL=%s %s %s %s 0 2' >> /etc/fstab\n", spec.Label, spec.Mount, spec.FS, mountOptions))
		b.WriteString("fi\n")
	}

	b.WriteString("\nsystemctl daemon-reload\n")
	b.WriteString("mount -a\n\n")

	for _, disk := range disks {
		if !disk.Spec.NeedsGuestSetup() {
			continue
		}
		b.WriteString(fmt.Sprintf("if ! findmnt -n %s >/dev/null; then\n", disk.Spec.Mount))
		b.WriteString(fmt.Sprintf("  echo \"pve: %s is not mounted after mount -a\" >&2\n", disk.Spec.Mount))
		b.WriteString("  exit 1\n")
		b.WriteString("fi\n")
	}
	b.WriteString("echo \"pve: data disk setup complete\"\n")
	return b.String()
}

// diskSetupCommand wraps the rendered script into a single remote command.
//
// The script travels base64-encoded so nothing in it has to survive shell
// quoting twice, and it runs through sudo because the cloud-init user is not
// root — passwordless sudo is already a documented template requirement.
func diskSetupCommand(script string) string {
	return fmt.Sprintf("echo %s | base64 -d | sudo bash -s", base64.StdEncoding.EncodeToString([]byte(script)))
}

// setupGuestDisks formats and mounts every attached disk that asked for it.
//
// It runs inside Create, before Rancher's system-agent bootstrap starts: a node
// must never join the cluster with its storage directory unmounted, because the
// storage provisioner would happily start filling the root filesystem instead.
func (d *Driver) setupGuestDisks(disks []proxmox.AttachedDisk) error {
	pending := make([]proxmox.AttachedDisk, 0, len(disks))
	for _, disk := range disks {
		if disk.Spec.NeedsGuestSetup() {
			pending = append(pending, disk)
		}
	}
	if len(pending) == 0 {
		return nil
	}

	timeout := d.DiskSetupTimeout
	if timeout <= 0 {
		timeout = defaultDiskSetupTimeout
	}

	done := make(chan error, 1)
	go func() {
		log.Infof("pve: waiting for SSH on %s to set up %d data disk(s)", d.IPAddress, len(pending))
		if err := drivers.WaitForSSH(d); err != nil {
			done <- fmt.Errorf("pve: SSH never became available for data disk setup: %w", err)
			return
		}
		out, err := drivers.RunSSHCommandFromDriver(d, diskSetupCommand(renderDiskSetupScript(pending)))
		if err != nil {
			done <- fmt.Errorf("pve: data disk setup failed: %w (guest output: %s)", err, strings.TrimSpace(out))
			return
		}
		log.Infof("pve: data disk setup finished: %s", strings.TrimSpace(out))
		done <- nil
	}()

	select {
	case err := <-done:
		return err
	case <-time.After(timeout):
		return fmt.Errorf("pve: data disk setup did not finish within %s (raise --pve-disk-setup-timeout)", timeout)
	}
}
