#!/bin/bash
# Generated by the pve node driver. Safe to re-run: a device that already has a
# filesystem is never reformatted and an fstab entry is never duplicated.
set -euo pipefail

# scsi1 -> /var/lib/longhorn (ext4, serial pvedata1)
dev=$(lsblk -ndo NAME,SERIAL | awk '$2=="pvedata1"{print "/dev/"$1}')
if [ -z "$dev" ]; then
  echo "pve: no block device with serial pvedata1" >&2
  exit 1
fi
if ! blkid "$dev" >/dev/null 2>&1; then
  mkfs.ext4 -q -L pvedata1 "$dev"
fi
mkdir -p /var/lib/longhorn
if ! grep -qF ' /var/lib/longhorn ' /etc/fstab; then
  echo 'LABEL=pvedata1 /var/lib/longhorn ext4 defaults,nofail,x-systemd.device-timeout=30s 0 2' >> /etc/fstab
fi

# scsi2 -> /var/lib/rancher (xfs, serial pvedata2)
dev=$(lsblk -ndo NAME,SERIAL | awk '$2=="pvedata2"{print "/dev/"$1}')
if [ -z "$dev" ]; then
  echo "pve: no block device with serial pvedata2" >&2
  exit 1
fi
if ! blkid "$dev" >/dev/null 2>&1; then
  mkfs.xfs -q -L pvedata2 "$dev"
fi
mkdir -p /var/lib/rancher
if ! grep -qF ' /var/lib/rancher ' /etc/fstab; then
  echo 'LABEL=pvedata2 /var/lib/rancher xfs defaults,nofail,x-systemd.device-timeout=30s 0 2' >> /etc/fstab
fi

systemctl daemon-reload
mount -a

if ! findmnt -n /var/lib/longhorn >/dev/null; then
  echo "pve: /var/lib/longhorn is not mounted after mount -a" >&2
  exit 1
fi
if ! findmnt -n /var/lib/rancher >/dev/null; then
  echo "pve: /var/lib/rancher is not mounted after mount -a" >&2
  exit 1
fi
echo "pve: data disk setup complete"
